### PR TITLE
Migrate from web components to vue

### PR DESCRIPTION
**Pull request by jsakas**
Vue handles a lot of things automatically, provides logic and loops in the HTML template string, and has some cool syntax for automatically binding object properties to the main synth instance. Ultimately the UI is exactly the same but it has better browser support and the overall syntax is cleaner and will be easier to extend in the future.

Also refactored the midi and querty input into their own controllers, mouse clicks are still handled by the component as event listeners on the instance.

Refactored the keyboard so it is rendered dynamically, which allows us to show more keys.

Added the ability to click and drag across the keyboard which is what a lot of other digital keyboards allow. 

Moved some other things out of the main Subtractor class as it is starting to get large and unmanageable. Subtractor should only be responsible for routing audio and updating itself via setters. Everything else (e.g. presets files, midi, etc) should be handled elsewhere.

### CODE REVIEW

**Comment by jsakas** [comment]
@stealthybox check it out, I upgraded the keyboard a bit: https://5cbe77f2cf74890009babeb9--subtractor.netlify.com/

**Comment by stealthybox** [comment]
Mouse/Keyboard input isn't working for me on Firefox Quantum 66.0.3 (64-bit) (Ubuntu).
I'll try another browser soon.

**Comment by jsakas** [comment]
@stealthybox I think I put this up a little too early. I have another branch I am working off of that has a lot of bug fixes. Will post soon.

**Comment by jsakas** [comment]
Firefox bug is fixed in https://github.com/jsakas/Subtractor/pull/72

**Pull request merged**
